/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plh24_ge3;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Comparator;
import java.util.Date;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

public class StatisticsPerYearMonth extends javax.swing.JFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("plh24_ge3PU");
    EntityManager em = emf.createEntityManager();
    GameJpaController gjc = new GameJpaController(emf);

    boolean finished = false; //μεταβλητή για να ελέγξω αν έχει τελειώσει η αρχικοποιήση της φόρμας

    /**
     * Creates new form StatisticsPerMonth
     */
    public StatisticsPerYearMonth() {

        //Listener ώστε να ξεκινήσω την διαδικασία όταν το παράθυρο θα έχει ανοίξει
        this.addWindowListener(new WindowAdapter() {
            // Invoked when a window has been opened.
            @Override
            public void windowOpened(WindowEvent e) {
                populateCmbs();
                finished = true;
            }
        });

        this.setTitle("Προβολή δεδομένων ΤΖΟΚΕΡ ανά μήνα για συγκεκριμένο έτος");//Τίτλος της φόρμας
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Επιλογή Έτους:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Επιλογή Μήνα:");

        jButton1.setText("Εμφάνιση Στατιστικών");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        StatistictsPerMonth spm = new StatistictsPerMonth();
        spm.setYear(jComboBox1.getSelectedItem().toString()); //Περνάω το έτος που επέλεξε ο χρήστης στην επόμενη οθόνη

        //Περνάω τον αριθμό του μήνα που επέλεξε ο χρήστης στην επόμενη οθόνη
        Date date = null;
        try {
            date = new SimpleDateFormat("MMMM", Locale.getDefault()).parse(jComboBox2.getSelectedItem().toString());
        } catch (ParseException ex) {
            Logger.getLogger(StatisticsPerYearMonth.class.getName()).log(Level.SEVERE, null, ex);
        }
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);

        spm.setMonth(cal.get(Calendar.MONTH) + 1);
        spm.pack();
        spm.setLocationRelativeTo(null);
        spm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (!finished) {
            return;
        }
        populateCmbs();
    }//GEN-LAST:event_jComboBox1ActionPerformed

//Γέμισμα των comboboxes
    private void populateCmbs() {
        try {
            //Επιλέγω όλες τις εγγραφές από τον πίνακα GAME
            em.getTransaction().begin();
            Query query = em.createNamedQuery("Game.findAll");

            //λίστα αντικειμένων games
            List<Game> games = new ArrayList<>();
            games = query.getResultList();
            em.getTransaction().commit();

            games.sort(Comparator.comparing(Game::getDrawdate));//Ταξινομώ την λίστα με τα αποτελέσματα από το query με βάση τις ημερομηνίες

            //Λίστα που θα αποθηκευθούν οι χρονιές για τις οποίες έχουμε αποθηκευμένα δεδομένα
            //Χρησιμοποιώ LinkedHashSet καθώς δεν επιτρέπει τα διπλότυπα
            LinkedHashSet<Integer> years = new LinkedHashSet<>();
            for (Game game : games) {
                //Αποθηκεύω στην LinkedHashSet μόνο τις χρονιές
                Date date = game.getDrawdate();
                Calendar cal = Calendar.getInstance(TimeZone.getDefault());
                cal.setTime(date);
                years.add(cal.get(Calendar.YEAR));
            }

            //Προσθήκη των ετών στο comboBox πριν αρχικοποιηθεί η φόρμα ΜΟΝΟ
            if (!finished) {
                jComboBox1.removeAllItems();
                years.forEach((year) -> {
                    jComboBox1.addItem(String.valueOf(year));
                });
            }

            //Προσθήκη μηνών στο 2ο Combobox αφού έχει επιλεχθεί η χρονία στο 1ο combobox
            LinkedHashSet<Integer> months = new LinkedHashSet<>();
            for (Game game : games) {
                //Αποθηκεύω στην LinkedHashSet μόνο τις χρονιές
                Date date = game.getDrawdate();
                Calendar cal = Calendar.getInstance(TimeZone.getDefault());
                cal.setTime(date);
                if (cal.get(Calendar.YEAR) == Integer.parseInt(jComboBox1.getSelectedItem().toString())) {
                    months.add(cal.get(Calendar.MONTH));
                }
            }
            jComboBox2.removeAllItems();
            months.forEach((month) -> {
                jComboBox2.addItem(getMonthDate(month));
            });
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String getMonthDate(int month) {
        switch (month) {
            case 0:
                return "Ιανουάριος";
            case 1:
                return "Φεβρουάριος";
            case 2:
                return "Μάρτιος";
            case 3:
                return "Απρίλιος";
            case 4:
                return "Μάιος";
            case 5:
                return "Ιούνιος";
            case 6:
                return "Ιούλιος";
            case 7:
                return "Αύγουστος";
            case 8:
                return "Σεπτέμβριος";
            case 9:
                return "Οκτώβριος";
            case 10:
                return "Νοέμβριος";
            case 11:
                return "Δεκέμβριος";
            default:
                return "";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsPerYearMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsPerYearMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsPerYearMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsPerYearMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsPerYearMonth().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
